### PR TITLE
Change the Multimap module to ES6 Map.

### PR DESCRIPTION
**Pull request by knightburton**
IoT.jsCode-DCO-1.0-Signed-off-by: Imre Kiss kissi.szeged@partner.samsung.com

### CODE REVIEW

**Comment by rtakacs** [comment]
LGTM

**Comment by yichoi** [comment]
@knightburton please rebase this PR to the master

**Comment by knightburton** [comment]
@rtakacs, @yichoi I've rebased the PR to the master.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
