### PR TITLE
Change the static getter functions to export const in some module.

### PR DESCRIPTION
**Pull request by knightburton**
IoT.jsCode-DCO-1.0-Signed-off-by: Imre Kiss kissi.szeged@partner.samsung.com

### CODE REVIEW

**Comment by rtakacs** [comment]
LGTM

**Comment by yichoi** [comment]
@knightburton rebase please

**Comment by knightburton** [comment]
@yichoi I've rebased the PR to the master.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
